version: "3.4"
services:
  kaggle-base:
    build: .
    image: youodf/kaggle-base
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
