version: "3.2"
services:
  jupyter:
    build: .
    image: youodf/jupyter
    ports:
      - "${JUPYTER_PORT}:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
