version: "3.2"
services:
  jupyter:
    build: .
    image: youodf/jupyter
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PROJECT_DIR=/app
    volumes:
      - .:/app
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root

  postgres:
    build: 
      context: ./postgres
      dockerfile: ./Dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    hostname: postgres

  pgweb:
    build: ./pgweb
    ports:
     - "${PGWEB_PORT}:8081"
    environment:
     - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${PROJECT_NAME}?sslmode=disable
     - AUTH_USER=${PGWEB_USER}
     - AUTH_PASS=${PGWEB_PASSWORD}
    depends_on:
     - postgres